#!/usr/bin/env ruby

# Read indata
@monkey = gets.chomp
@remaining_capacity = Integer(gets.chomp)
@num_requests = Integer(gets.chomp)
@width = Integer(gets.chomp)
@height = Integer(gets.chomp)

# Read level
@tracks = []
@height.times do |y|
  row = gets.chomp.split(',')
  @width.times do |x|
    thing = row[x]
    if thing == @monkey
      @x, @y = x, y
    elsif /spotify:track/.match(thing)
      @tracks << [x, y]
    elsif thing == "U"
      @user = [x, y]
    end
  end
end

def move_toward(x, y)
  if @x < x
    "E"
  elsif @x > x
    "W"
  elsif @y < y
    "S"
  elsif @y > y
    "N"
  end
end

def closest_track
  curr_closest = @tracks.pop()
  curr_smallest_distance = distance_to(*curr_closest)
  @tracks.each do |track|
    curr_distance = distance_to(*track)
    if curr_distance < curr_smallest_distance
      curr_closest = track
      curr_smallest_distance = curr_distance
    end
  end
  curr_closest
end

def distance_to(x, y)
  (@x - x).abs + (@y - y).abs
end

if (@remaining_capacity > 0) && (not @tracks.empty?)
  puts move_toward(*closest_track())
else
  puts move_toward(*@user)
end
